# Netlify deployment configuration

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Next.js environment variables
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_FLAGS = "--force"

# Plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
