# Netlify deployment configuration

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Next.js environment variables
  NEXT_TELEMETRY_DISABLED = "1"

# Environment variable configuration
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Headers configuration (additional to Next.js headers)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# API route handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Function configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Post-processing
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
